services:
  activity-worker:
    container_name: activity-worker
    build:
      context: ./
      dockerfile: activity-worker/Dockerfile
      args:
        - PHP_USER=temporal
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
     - ../../temporal-apps/activity-worker:/var/www
    environment:
      - WORKFLOW_TASK_QUEUE=workflow.queue
      - ACTIVITY_TASK_QUEUE=activity.queue
      - TEMPORAL_SERVER_ENDPOINT=temporal.addr:7233
      - TELEMETRY_DRIVER=otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.addr:4318
      - OTEL_PHP_TRACES_PROCESSOR=simple
      - TEMPORAL_HOST=temporal.addr
      - OTEL_HOST=collector.addr
      # - INTERCEPTORS_RR_PATH=/usr/local/bin/rr
    extra_hosts:
      - "temporal.addr=host-gateway"
      - "collector.addr=host-gateway"
    command: [ "/usr/local/bin/rr", "serve", "-c", "/var/www/rr.yaml" ]

  workflow-worker:
    container_name: workflow-worker
    build:
      context: ./
      dockerfile: workflow-worker/Dockerfile
      args:
        - PHP_USER=temporal
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
     - ../../temporal-apps/workflow-worker:/var/www
    environment:
      - WORKFLOW_TASK_QUEUE=workflow.queue
      - ACTIVITY_TASK_QUEUE=activity.queue
      - TEMPORAL_SERVER_ENDPOINT=temporal.addr:7233
      - TELEMETRY_DRIVER=otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.addr:4318
      - OTEL_PHP_TRACES_PROCESSOR=simple
      - TEMPORAL_HOST=temporal.addr
      - OTEL_HOST=collector.addr
      # - INTERCEPTORS_RR_PATH=/usr/local/bin/rr
    extra_hosts:
      - "temporal.addr=host-gateway"
      - "collector.addr=host-gateway"
    command: [ "/usr/local/bin/rr", "serve", "-c", "/var/www/rr.yaml" ]

  workflow-api-nginx-phpfpm:
    container_name: workflow-api-nginx-phpfpm
    build:
      context: ./
      dockerfile: workflow-api/nginx-phpfpm/Dockerfile
      args:
        - PHP_USER=temporal
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
     - ../../temporal-apps/workflow-api:/var/www
    environment:
      - WORKFLOW_TASK_QUEUE=workflow.queue
      - ACTIVITY_TASK_QUEUE=activity.queue
      - TEMPORAL_SERVER_ENDPOINT=temporal.addr:7233
      - TELEMETRY_DRIVER=otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.addr:4318
      - OTEL_PHP_TRACES_PROCESSOR=simple
      - TEMPORAL_HOST=temporal.addr
      - OTEL_HOST=collector.addr
      # - INTERCEPTORS_RR_PATH=/usr/local/bin/rr
    ports:
      - 9300:80
    extra_hosts:
      - "temporal.addr=host-gateway"
      - "collector.addr=host-gateway"
    command: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
